/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.efimovta.liferay.osgi.db.weather.model;

import aQute.bnd.annotation.ProviderType;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;
import java.util.Date;

/**
 * The base model interface for the Weather service. Represents a row in the &quot;Weatherdb_Weather&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.efimovta.liferay.osgi.db.weather.model.impl.WeatherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.efimovta.liferay.osgi.db.weather.model.impl.WeatherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Weather
 * @see edu.efimovta.liferay.osgi.db.weather.model.impl.WeatherImpl
 * @see edu.efimovta.liferay.osgi.db.weather.model.impl.WeatherModelImpl
 * @generated
 */
@ProviderType
public interface WeatherModel extends BaseModel<Weather>, GroupedModel,
        ShardedModel {
    /*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a weather model instance should use the {@link Weather} interface instead.
	 */

    /**
     * Returns the primary key of this weather.
     *
     * @return the primary key of this weather
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this weather.
     *
     * @param primaryKey the primary key of this weather
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the weather ID of this weather.
     *
     * @return the weather ID of this weather
     */
    public long getWeatherId();

    /**
     * Sets the weather ID of this weather.
     *
     * @param weatherId the weather ID of this weather
     */
    public void setWeatherId(long weatherId);

    /**
     * Returns the group ID of this weather.
     *
     * @return the group ID of this weather
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this weather.
     *
     * @param groupId the group ID of this weather
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this weather.
     *
     * @return the company ID of this weather
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this weather.
     *
     * @param companyId the company ID of this weather
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this weather.
     *
     * @return the user ID of this weather
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this weather.
     *
     * @param userId the user ID of this weather
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this weather.
     *
     * @return the user uuid of this weather
     */
    @Override
    public String getUserUuid();

    /**
     * Sets the user uuid of this weather.
     *
     * @param userUuid the user uuid of this weather
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this weather.
     *
     * @return the user name of this weather
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this weather.
     *
     * @param userName the user name of this weather
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this weather.
     *
     * @return the create date of this weather
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this weather.
     *
     * @param createDate the create date of this weather
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this weather.
     *
     * @return the modified date of this weather
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this weather.
     *
     * @param modifiedDate the modified date of this weather
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the search param city of this weather.
     *
     * @return the search param city of this weather
     */
    @AutoEscape
    public String getSearchParamCity();

    /**
     * Sets the search param city of this weather.
     *
     * @param searchParamCity the search param city of this weather
     */
    public void setSearchParamCity(String searchParamCity);

    /**
     * Returns the search param date of this weather.
     *
     * @return the search param date of this weather
     */
    public Date getSearchParamDate();

    /**
     * Sets the search param date of this weather.
     *
     * @param searchParamDate the search param date of this weather
     */
    public void setSearchParamDate(Date searchParamDate);

    /**
     * Returns the source of this weather.
     *
     * @return the source of this weather
     */
    @AutoEscape
    public String getSource();

    /**
     * Sets the source of this weather.
     *
     * @param source the source of this weather
     */
    public void setSource(String source);

    /**
     * Returns the city of this weather.
     *
     * @return the city of this weather
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this weather.
     *
     * @param city the city of this weather
     */
    public void setCity(String city);

    /**
     * Returns the country of this weather.
     *
     * @return the country of this weather
     */
    @AutoEscape
    public String getCountry();

    /**
     * Sets the country of this weather.
     *
     * @param country the country of this weather
     */
    public void setCountry(String country);

    /**
     * Returns the lat of this weather.
     *
     * @return the lat of this weather
     */
    public double getLat();

    /**
     * Sets the lat of this weather.
     *
     * @param lat the lat of this weather
     */
    public void setLat(double lat);

    /**
     * Returns the lon of this weather.
     *
     * @return the lon of this weather
     */
    public double getLon();

    /**
     * Sets the lon of this weather.
     *
     * @param lon the lon of this weather
     */
    public void setLon(double lon);

    /**
     * Returns the condition of this weather.
     *
     * @return the condition of this weather
     */
    @AutoEscape
    public String getCondition();

    /**
     * Sets the condition of this weather.
     *
     * @param condition the condition of this weather
     */
    public void setCondition(String condition);

    /**
     * Returns the avg temp of this weather.
     *
     * @return the avg temp of this weather
     */
    public double getAvgTemp();

    /**
     * Sets the avg temp of this weather.
     *
     * @param avgTemp the avg temp of this weather
     */
    public void setAvgTemp(double avgTemp);

    /**
     * Returns the min temp of this weather.
     *
     * @return the min temp of this weather
     */
    public double getMinTemp();

    /**
     * Sets the min temp of this weather.
     *
     * @param minTemp the min temp of this weather
     */
    public void setMinTemp(double minTemp);

    /**
     * Returns the max temp of this weather.
     *
     * @return the max temp of this weather
     */
    public double getMaxTemp();

    /**
     * Sets the max temp of this weather.
     *
     * @param maxTemp the max temp of this weather
     */
    public void setMaxTemp(double maxTemp);

    /**
     * Returns the date of this weather.
     *
     * @return the date of this weather
     */
    public Date getDate();

    /**
     * Sets the date of this weather.
     *
     * @param date the date of this weather
     */
    public void setDate(Date date);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
            edu.efimovta.liferay.osgi.db.weather.model.Weather weather);

    @Override
    public int hashCode();

    @Override
    public CacheModel<edu.efimovta.liferay.osgi.db.weather.model.Weather> toCacheModel();

    @Override
    public edu.efimovta.liferay.osgi.db.weather.model.Weather toEscapedModel();

	@Override
    public edu.efimovta.liferay.osgi.db.weather.model.Weather toUnescapedModel();

	@Override
    public String toString();

	@Override
    public String toXmlString();
}